name: Tagged Release

on:
  push:
    tags:
      - "*"
jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    # compile the code and build the deb package
    # this step is project specific
    # in the end just a .deb package is required
    - name: Compile
      run: |
        echo "tagname: $GITHUB_REF_NAME"
        cd src
        gcc -O3 helloworld.c -o helloworld
        cd ..
        mkdir -p helloworld-$GITHUB_REF_NAME/usr/local/bin
        mkdir -p helloworld-$GITHUB_REF_NAME/DEBIAN
        cp DEBIAN/control helloworld-$GITHUB_REF_NAME/DEBIAN
        cp src/helloworld helloworld-$GITHUB_REF_NAME/usr/local/bin

        sudo chown -R 0:0 helloworld-$GITHUB_REF_NAME/
        dpkg -b helloworld-$GITHUB_REF_NAME

    #  now comes the interessting part
    #  we need to clone the ppa repository
    - uses: actions/checkout@v4
      name: Upload to ppa
      with:
        repository: JayPi4c/ppa
        path: ppa
        token: ${{ secrets.PAT }}
    - name: setup git config
      run: |
        cp helloworld-$GITHUB_REF_NAME.deb ppa/ubuntu/
        cd ppa
        git config user.name "Package deployer (Bot)"
        git config user.email "<>"
        git add .
        git commit -m "ExampleDebianPackage $GITHUB_REF_NAME"
        git push