name: Tagged Release

on:
  push:
    tags:
      - "*"
jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Compile
      run: |
        echo "tagname: $GITHUB_REF_NAME"
        cd src
        gcc -O3 helloworld.c -o helloworld
        cd ..
        mkdir -p helloworld-$GITHUB_REF_NAME/usr/local/bin
        mkdir -p helloworld-$GITHUB_REF_NAME/usr/local/bin
        cp DEBIAN/control helloworld-$GITHUB_REF_NAME/DEBIAN

        sudo chown -R 0:0 helloworld-$GITHUB_REF_NAME/
        dpkg -b helloworld-$GITHUB_REF_NAME
        ls
    